In [1]:
import numpy as np
import pandas as pd

In [6]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 30)
pd.set_option('display.precision', 3)

In [4]:
pd_version = pd.__version__
np_version = np.__version__

In [7]:
olive_path = './olive.csv'

In [12]:
# cols = ['region', 'area', 'palmitic', 'palmitoleic', 'stearic',
#         'oleic', 'linoleic', 'linolenic', 'arachidic', 'eicosenoic']

df = pd.read_csv(olive_path)

In [15]:
df_shape = df.shape
# df_shape

(572, 11)

In [17]:
df_first_two = df[0:2]
# df_first_two.head()

Unnamed: 0  region  area  palmitic  palmitoleic  stearic  oleic  \
0  1.North-Apulia       1     1      1075           75      226   7823   
1  2.North-Apulia       1     1      1088           73      224   7709   

   linoleic  linolenic  arachidic  eicosenoic  
0       672         36         60          29  
1       781         31         61          29

In [21]:
df_data_types_count = len(df.dtypes.unique())
# df_data_types_count

2

In [24]:
df['sub_region_raw'] = df['Unnamed: 0'].copy()
# df.head()

Unnamed: 0  region  area  palmitic  palmitoleic  stearic  oleic  \
0  1.North-Apulia       1     1      1075           75      226   7823   
1  2.North-Apulia       1     1      1088           73      224   7709   
2  3.North-Apulia       1     1       911           54      246   8113   
3  4.North-Apulia       1     1       966           57      240   7952   
4  5.North-Apulia       1     1      1051           67      259   7771   

   linoleic  linolenic  arachidic  eicosenoic  sub_region_raw  
0       672         36         60          29  1.North-Apulia  
1       781         31         61          29  2.North-Apulia  
2       549         31         63          29  3.North-Apulia  
3       619         50         78          35  4.North-Apulia  
4       672         50         80          46  5.North-Apulia

In [25]:
df.rename(columns={'Unnamed: 0': 'sub_region_desc'}, inplace=True)
# df.head()

sub_region_desc  region  area  palmitic  palmitoleic  stearic  oleic  \
0  1.North-Apulia       1     1      1075           75      226   7823   
1  2.North-Apulia       1     1      1088           73      224   7709   
2  3.North-Apulia       1     1       911           54      246   8113   
3  4.North-Apulia       1     1       966           57      240   7952   
4  5.North-Apulia       1     1      1051           67      259   7771   

   linoleic  linolenic  arachidic  eicosenoic  sub_region_raw  
0       672         36         60          29  1.North-Apulia  
1       781         31         61          29  2.North-Apulia  
2       549         31         63          29  3.North-Apulia  
3       619         50         78          35  4.North-Apulia  
4       672         50         80          46  5.North-Apulia

In [26]:
df.rename(columns={'area': 'sub_region'}, inplace=True)
# df.head()

sub_region_desc  region  sub_region  palmitic  palmitoleic  stearic  oleic  \
0  1.North-Apulia       1           1      1075           75      226   7823   
1  2.North-Apulia       1           1      1088           73      224   7709   
2  3.North-Apulia       1           1       911           54      246   8113   
3  4.North-Apulia       1           1       966           57      240   7952   
4  5.North-Apulia       1           1      1051           67      259   7771   

   linoleic  linolenic  arachidic  eicosenoic  sub_region_raw  
0       672         36         60          29  1.North-Apulia  
1       781         31         61          29  2.North-Apulia  
2       549         31         63          29  3.North-Apulia  
3       619         50         78          35  4.North-Apulia  
4       672         50         80          46  5.North-Apulia

In [27]:
region_unique = df.region.unique()
# region_unique

array([1, 2, 3])

In [28]:
sub_region_unique_count = len(df.sub_region.unique())
# sub_region_unique_count

9

In [39]:
import re

row_num_re = re.compile(r'\d+.')

df['sub_region_desc'].replace(row_num_re, '', inplace=True)

srd_unique = df.sub_region_desc.unique()

In [41]:
A = np.array([[1, 2, 3], [2, 7, 4]])
B = np.array([[1, -1], [0, 1]])
A.T.dot(B)

array([[1, 1],
       [2, 5],
       [3, 1]])

In [42]:
B @ B @ B @ B

array([[ 1, -4],
       [ 0,  1]])

In [47]:
B ** 4

array([[1, 1],
       [0, 1]])

In [45]:
A.

AttributeError: module 'numpy' has no attribute 'norm'